apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat #filebeat is getting i/p from access,error.lod and pushing it to elastic search(log storage)
data:
  filebeat.yml: |
    filebeat:
      config:
        modules:
          path: /usr/share/filebeat/modules.d/*.yml
          reload:
            enabled: true
      modules:
      - module: nginx
        access:
          var.paths: ["/var/log/nginx/access.log*"]
        error:
          var.paths: ["/var/log/nginx/error.log*"]
    output:
      elasticsearch:
        hosts: ["elasticsearch:9200"] 
---
kind: Pod
apiVersion: v1
metadata:
  name: nginx
spec:
  containers: #in pod we have 2 containers
  - name: nginx #main container
    image: nginx #nginx image
    volumeMounts:
    - name: nginx-logs
      mountPath: /var/log/nginx/
  - name: filebeat #sidecar container
    image: docker.elastic.co/beats/filebeat:7.5.0 #filebeat image
    volumeMounts:
    - name: filebeat-config
      mountPath: /usr/share/filebeat/filebeat.yml
      subPath: filebeat.yml
    - name: nginx-logs
      mountPath: /var/log/nginx/ #now filebeat wil access the files in this nginx location
  volumes: #in which location we need the logs
  - name: nginx-logs
    emptyDir: {}
  - name: filebeat-config
    configMap:
      name: filebeat
      items:
        - key: filebeat.yml
          path: filebeat.yml