#here if i taint a perticular node with some key,value and actions(no schedule etc)
#then schedular by default wil not schedule pods in that node, 
#but k8s wil allow the pods only which have tolerations
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always # keep this as always
  tolerations: 
  - key: "project"
    operator: "Equal"
    value: "expense"
    effect: "NoSchedule"
  - key: "project"
    operator: "Exists"
    effect: "NoSchedule"