apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    name: pod-1
    purpose: affinity
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always # keep this as always
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    name: pod-1
    purpose: affinity
spec:
  affinity:
    podAffinity: #run the pod-2 werevr pod-1 is located ie node-1
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: name
            operator: In
            values:
            - pod-1
        topologyKey: topology.kubernetes.io/zone #for pod affinity
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always # keep this as always
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-3
  labels:
    name: pod-3
    purpose: affinity
spec:
  affinity:
    podAntiAffinity: #means pod-3 hates to be with pod-1 ie in node-1
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: name
            operator: In
            values:
            - pod-1
        topologyKey: "kubernetes.io/hostname" #for pod anti affinity
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always # keep this as always