apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static #pv volume name
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-081e973dd32bba47e
---
#pvc
apiVersion: v1
kind: PersistentVolumeClaim #now pods wil claim the volume from 100gb
metadata:
  name: ebs-static #from which volume u r claiming ie: pv volume
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce #EBS/hard disk can access only server
  resources:
    requests:
      storage: 5Gi #pod is claiming 5gb out of 100gb
---
#pod def
apiVersion: v1
kind: Pod #that pvc claim we need to mention in pod defi here
metadata:
  name: nginx-static
  labels:
    purpose: ebs-static
    project: expense
spec:
  containers:
  - name: nginx #this wil get root access bcz this image is from internet, we r not created,
    image: nginx #normal user cant acces port 80 in k8 cluster
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html #nginx html path
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c #we can select wer our pod can go , in us-east-1c we created EBS
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-static
---
#LB-service
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector: #giv here pod labels
    purpose: ebs-static
    project: expense
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80